/* AUTO GENERATED CODE */
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/clientset/versioned/typed/waitingroom/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeLineqV1alpha1 struct {
	*testing.Fake
}

func (c *FakeLineqV1alpha1) WaitingRooms(namespace string) v1alpha1.WaitingRoomInterface {
	return &FakeWaitingRooms{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeLineqV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
