/* AUTO GENERATED CODE */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// WaitingRooms returns a WaitingRoomInformer.
	WaitingRooms() WaitingRoomInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// WaitingRooms returns a WaitingRoomInformer.
func (v *version) WaitingRooms() WaitingRoomInformer {
	return &waitingRoomInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
