/* AUTO GENERATED CODE */
// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	waitingroomv1alpha1 "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1"
	versioned "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/clientset/versioned"
	internalinterfaces "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/listers/waitingroom/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// WaitingRoomInformer provides access to a shared informer and lister for
// WaitingRooms.
type WaitingRoomInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.WaitingRoomLister
}

type waitingRoomInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewWaitingRoomInformer constructs a new informer for WaitingRoom type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewWaitingRoomInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredWaitingRoomInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredWaitingRoomInformer constructs a new informer for WaitingRoom type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredWaitingRoomInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LineqV1alpha1().WaitingRooms(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.LineqV1alpha1().WaitingRooms(namespace).Watch(context.TODO(), options)
			},
		},
		&waitingroomv1alpha1.WaitingRoom{},
		resyncPeriod,
		indexers,
	)
}

func (f *waitingRoomInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredWaitingRoomInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *waitingRoomInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&waitingroomv1alpha1.WaitingRoom{}, f.defaultInformer)
}

func (f *waitingRoomInformer) Lister() v1alpha1.WaitingRoomLister {
	return v1alpha1.NewWaitingRoomLister(f.Informer().GetIndexer())
}
