/* AUTO GENERATED CODE */
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// WaitingRoomListerExpansion allows custom methods to be added to
// WaitingRoomLister.
type WaitingRoomListerExpansion interface{}

// WaitingRoomNamespaceListerExpansion allows custom methods to be added to
// WaitingRoomNamespaceLister.
type WaitingRoomNamespaceListerExpansion interface{}
