/* AUTO GENERATED CODE */
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1"
	waitingroomv1alpha1 "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/applyconfiguration/waitingroom/v1alpha1"
	scheme "github.com/hamedetemaad/lineq-operator/pkg/waitingroom/v1alpha1/apis/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// WaitingRoomsGetter has a method to return a WaitingRoomInterface.
// A group's client should implement this interface.
type WaitingRoomsGetter interface {
	WaitingRooms(namespace string) WaitingRoomInterface
}

// WaitingRoomInterface has methods to work with WaitingRoom resources.
type WaitingRoomInterface interface {
	Create(ctx context.Context, waitingRoom *v1alpha1.WaitingRoom, opts v1.CreateOptions) (*v1alpha1.WaitingRoom, error)
	Update(ctx context.Context, waitingRoom *v1alpha1.WaitingRoom, opts v1.UpdateOptions) (*v1alpha1.WaitingRoom, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.WaitingRoom, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.WaitingRoomList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WaitingRoom, err error)
	Apply(ctx context.Context, waitingRoom *waitingroomv1alpha1.WaitingRoomApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WaitingRoom, err error)
	WaitingRoomExpansion
}

// waitingRooms implements WaitingRoomInterface
type waitingRooms struct {
	client rest.Interface
	ns     string
}

// newWaitingRooms returns a WaitingRooms
func newWaitingRooms(c *LineqV1alpha1Client, namespace string) *waitingRooms {
	return &waitingRooms{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the waitingRoom, and returns the corresponding waitingRoom object, and an error if there is any.
func (c *waitingRooms) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.WaitingRoom, err error) {
	result = &v1alpha1.WaitingRoom{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("waitingrooms").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of WaitingRooms that match those selectors.
func (c *waitingRooms) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.WaitingRoomList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.WaitingRoomList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("waitingrooms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested waitingRooms.
func (c *waitingRooms) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("waitingrooms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a waitingRoom and creates it.  Returns the server's representation of the waitingRoom, and an error, if there is any.
func (c *waitingRooms) Create(ctx context.Context, waitingRoom *v1alpha1.WaitingRoom, opts v1.CreateOptions) (result *v1alpha1.WaitingRoom, err error) {
	result = &v1alpha1.WaitingRoom{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("waitingrooms").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(waitingRoom).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a waitingRoom and updates it. Returns the server's representation of the waitingRoom, and an error, if there is any.
func (c *waitingRooms) Update(ctx context.Context, waitingRoom *v1alpha1.WaitingRoom, opts v1.UpdateOptions) (result *v1alpha1.WaitingRoom, err error) {
	result = &v1alpha1.WaitingRoom{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("waitingrooms").
		Name(waitingRoom.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(waitingRoom).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the waitingRoom and deletes it. Returns an error if one occurs.
func (c *waitingRooms) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("waitingrooms").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *waitingRooms) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("waitingrooms").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched waitingRoom.
func (c *waitingRooms) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.WaitingRoom, err error) {
	result = &v1alpha1.WaitingRoom{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("waitingrooms").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied waitingRoom.
func (c *waitingRooms) Apply(ctx context.Context, waitingRoom *waitingroomv1alpha1.WaitingRoomApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.WaitingRoom, err error) {
	if waitingRoom == nil {
		return nil, fmt.Errorf("waitingRoom provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(waitingRoom)
	if err != nil {
		return nil, err
	}
	name := waitingRoom.Name
	if name == nil {
		return nil, fmt.Errorf("waitingRoom.Name must be provided to Apply")
	}
	result = &v1alpha1.WaitingRoom{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("waitingrooms").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
