//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/* AUTO GENERATED CODE */
// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitingRoom) DeepCopyInto(out *WaitingRoom) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitingRoom.
func (in *WaitingRoom) DeepCopy() *WaitingRoom {
	if in == nil {
		return nil
	}
	out := new(WaitingRoom)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaitingRoom) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitingRoomList) DeepCopyInto(out *WaitingRoomList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WaitingRoom, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitingRoomList.
func (in *WaitingRoomList) DeepCopy() *WaitingRoomList {
	if in == nil {
		return nil
	}
	out := new(WaitingRoomList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WaitingRoomList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WaitingRoomSpec) DeepCopyInto(out *WaitingRoomSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WaitingRoomSpec.
func (in *WaitingRoomSpec) DeepCopy() *WaitingRoomSpec {
	if in == nil {
		return nil
	}
	out := new(WaitingRoomSpec)
	in.DeepCopyInto(out)
	return out
}
